### ISSUE TITLE
Templates missing parameters

### ISSUE THREAD

**Issue by sbyount** [aristanetworks/cloudformation#2]
Hello, I attempted to use your spoke template to create a cloudformation stack with ansible, and got the following error.

`The error was: botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [SubnetId, VpcId, ImageId, InstanceType] do not exist in the template`

The task I ran includes these parameters, so I don't if this is an issue with the cloudformation module, or your template.

```
- name: Create a cloudformation stack
  amazon.aws.cloudformation:
    stack_name: ansible-cloudformation
    state: present
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    disable_rollback: true
    template: "./files/spokevpc.json"
    template_parameters:
      KeyName: "{{ key_name }}"
      InstanceType: "{{ instance_type }}"
      ImageId: "{{ image_id }}"
      VpcId: "{{ vpc_id }}"
      SubnetId: "{{ vpc_subnet_id }}"
  tags: Stack: ansible-cloudformation
register: cloudformation
```
